Name: **Zhenmin Hua**  
USC_ID: **5905057247**  
Github username: **Zeddhua2077**

# 552_hw3

In [19]:
import numpy as np
import pandas as pd
import os
from scipy import stats
from sklearn.preprocessing import StandardScaler
from sklearn.utils import resample

## Q1

### Q1.b

**under Q1.c.(ii)**

### Q1.c

#### Q1.c.(i)

There are
- Minimum
- Maximum
- Mean
- Median
- Standard Deviation
- First Quartile
- Third Quartile
- Mean Absolute Value
- Zero Crossings
- Slope Sign Changes
- Waveform Length
- Willison Amplitude
- Variance
- log-Detector
- Autoregression Coefficient

#### Q1.c.(ii)

In [20]:
def get_features(df1):    
    df1_des = df1.describe()
    df1_des.drop(['# Columns: time'], axis=1, inplace=True)
    df1_des.drop(['count'], axis=0, inplace=True)
    df1_des = df1_des.reindex(index=['min', 'max', 'mean', '50%', 'std', '25%', '75%'])
    df1_des.columns = [1, 2, 3, 4, 5, 6]
    df = pd.DataFrame()
    for i in range(1,7):
        df_T = pd.DataFrame(df1_des[i]).T.reset_index(drop=True)
        df_T = df_T.add_suffix('_'+str(i))
        df = pd.concat([df, df_T], axis=1)
    return df

df = pd.DataFrame()
df_test = pd.DataFrame()
df_train = pd.DataFrame()
fold_name = ['bending1', 'bending2', 'cycling', 'lying', 'sitting', 'standing', 'walking']
for name in fold_name:
    num = 1
    path = '../data/AReM/' + name + '/dataset1.csv'
    while(os.path.exists(path)):
        if name == 'bending2' and num == 4:
            df1 = pd.read_csv(path, sep=' ', skiprows=5, header=None)
            df1.drop([7], axis=1, inplace=True)
            df1.columns = ['# Columns: time', 1, 2, 3, 4, 5, 6]
        else:
            df1 = pd.read_csv(path, sep=',', skiprows=4)
        df = df.append(get_features(df1))
        num += 1
        path = '../data/AReM/' + name + '/dataset' + str(num) + '.csv'
        if (name == 'bending1' or name == 'bending2') and (num == 1 or num == 2):
            df_test = df_test.append(get_features(df1))
        elif (name != 'bending1' and name != 'bending2') and (num in [1,2,3]):
            df_test = df_test.append(get_features(df1))
        else:
            df_train = df_train.append(get_features(df1))

df = df.reset_index(drop=True)
df.index = df.index + 1
df.insert(0, 'Instance', range(1,len(df)+1))
df.to_csv('time_features.csv', index=False)

### Q1.b

In [21]:
#train_data
df_train

,min_1,max_1,mean_1,50%_1,std_1,25%_1,75%_1,min_2,max_2,mean_2,...,std_5,25%_5,75%_5,min_6,max_6,mean_6,50%_6,std_6,25%_6,75%_6
0,38.00,45.67,42.812812,42.50,1.435550,42.00,43.6700,0.0,1.22,0.372438,...,1.995255,32.0000,34.50,0.00,3.11,0.571083,0.43,0.601010,0.0000,1.3000
0,35.00,47.40,43.954500,44.33,1.558835,43.00,45.0000,0.0,1.70,0.426250,...,1.999604,35.3625,36.50,0.00,1.79,0.493292,0.43,0.513506,0.0000,0.9400
0,33.00,47.75,42.179813,43.50,3.670666,39.15,45.0000,0.0,3.00,0.696042,...,3.849448,30.4575,36.33,0.00,2.18,0.613521,0.50,0.524317,0.0000,1.0000
0,33.00,45.75,41.678063,41.75,2.243490,41.33,42.7500,0.0,2.83,0.535979,...,2.411026,28.4575,31.25,0.00,1.79,0.383292,0.43,0.389164,0.0000,0.5000
0,37.00,48.00,43.454958,43.25,1.386098,42.50,45.0000,0.0,1.58,0.378083,...,2.488862,22.2500,24.00,0.00,5.26,0.679646,0.50,0.622534,0.4300,0.8700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,19.50,45.33,33.586875,34.25,4.650935,30.25,37.0000,0.0,14.67,4.576562,...,3.283983,13.7300,18.25,0.00,8.32,3.259729,3.11,1.640243,2.0500,4.3225
0,19.75,45.50,34.322750,35.25,4.752477,31.00,38.0000,0.0,13.47,4.456333,...,3.119856,13.5000,17.75,0.00,9.67,3.432562,3.20,1.732727,2.1575,4.5650
0,19.50,46.00,34.546229,35.25,4.842294,31.25,37.8125,0.0,12.47,4.371958,...,2.823124,14.0000,17.75,0.00,10.00,3.338125,3.08,1.656742,2.1600,4.3350
0,23.50,46.25,34.873229,35.25,4.531720,31.75,38.2500,0.0,14.82,4.380583,...,3.131076,13.7500,18.00,0.00,9.51,3.424646,3.27,1.690960,2.1700,4.5000
0,19.25,44.00,34.473188,35.00,4.796705,31.25,38.0000,0.0,13.86,4.359312,...,3.156320,13.7300,17.75,0.43,9.00,3.340458,3.09,1.699114,2.1200,4.3750

In [22]:
#test_data
df_test

,min_1,max_1,mean_1,50%_1,std_1,25%_1,75%_1,min_2,max_2,mean_2,...,std_5,25%_5,75%_5,min_6,max_6,mean_6,50%_6,std_6,25%_6,75%_6
0,37.25,45.00,40.624792,40.500,1.476967,39.2500,42.00,0.0,1.30,0.358604,...,2.188449,33.0000,36.0000,0.0,1.92,0.570583,0.430,0.582915,0.0000,1.300
0,12.75,51.00,24.562958,24.250,3.737514,23.1875,26.50,0.0,6.87,0.590833,...,3.693786,20.5000,27.0000,0.0,4.97,0.700188,0.500,0.693720,0.4300,0.870
0,24.25,45.00,37.177042,36.250,3.581301,34.5000,40.25,0.0,8.58,2.374208,...,2.890347,17.9500,21.7500,0.0,9.34,2.921729,2.500,1.852600,1.5000,3.900
0,28.75,44.75,37.561188,36.875,3.226507,35.2500,40.25,0.0,9.91,2.080688,...,2.727377,18.0000,21.5000,0.0,9.62,2.765896,2.450,1.769203,1.4100,3.770
0,23.50,30.00,27.716375,27.500,1.442253,27.0000,29.00,0.0,1.79,0.363688,...,4.074511,5.5000,10.7500,0.0,4.50,0.734271,0.710,0.613688,0.4300,1.000
0,24.75,48.33,44.182937,48.000,7.495615,48.0000,48.00,0.0,3.11,0.101875,...,3.274539,2.0000,5.5425,0.0,3.91,0.692771,0.500,0.675781,0.3225,0.940
0,33.25,48.00,42.363563,43.000,2.068247,42.0000,43.50,0.0,4.44,0.492563,...,4.956821,10.1875,17.6900,0.0,6.02,1.034021,0.830,0.985627,0.4700,1.250
0,37.00,50.75,45.917667,45.635,1.089027,45.0000,46.50,0.0,4.87,0.324542,...,3.585511,16.5000,21.0000,0.0,7.22,0.904604,0.710,0.896171,0.4300,1.120
0,33.33,48.00,44.334729,45.000,2.476940,42.2500,46.50,0.0,3.90,0.432958,...,5.401794,9.3300,17.7500,0.0,5.02,0.933000,0.830,0.673609,0.4700,1.250
0,35.50,46.25,43.174938,43.670,1.989052,42.5000,44.50,0.0,2.12,0.506583,...,2.983976,12.7500,16.5000,0.0,5.72,0.911979,0.830,0.666161,0.4700,1.220
0,19.33,43.50,34.227771,35.500,4.889576,30.5000,37.75,0.0,14.50,3.995729,...,3.092094,14.7500,18.6700,0.0,9.74,3.394125,3.100,1.792090,2.1050,4.425
0,12.50,45.00,33.509729,34.125,4.850923,30.5000,36.75,0.0,13.05,4.450771,...,3.133564,14.6275,18.7500,0.0,8.96,3.378479,3.085,1.787360,2.0600,4.440

#### Q1.c.(iii)

In [23]:
df = pd.read_csv('time_features.csv')
df.head()

,Instance,min_1,max_1,mean_1,50%_1,std_1,25%_1,75%_1,min_2,max_2,...,std_5,25%_5,75%_5,min_6,max_6,mean_6,50%_6,std_6,25%_6,75%_6
0,1,37.25,45.00,40.624792,40.50,1.476967,39.25,42.00,0.0,1.30,...,2.188449,33.0000,36.00,0.0,1.92,0.570583,0.43,0.582915,0.0,1.30
1,2,38.00,45.67,42.812812,42.50,1.435550,42.00,43.67,0.0,1.22,...,1.995255,32.0000,34.50,0.0,3.11,0.571083,0.43,0.601010,0.0,1.30
2,3,35.00,47.40,43.954500,44.33,1.558835,43.00,45.00,0.0,1.70,...,1.999604,35.3625,36.50,0.0,1.79,0.493292,0.43,0.513506,0.0,0.94
3,4,33.00,47.75,42.179813,43.50,3.670666,39.15,45.00,0.0,3.00,...,3.849448,30.4575,36.33,0.0,2.18,0.613521,0.50,0.524317,0.0,1.00
4,5,33.00,45.75,41.678063,41.75,2.243490,41.33,42.75,0.0,2.83,...,2.411026,28.4575,31.25,0.0,1.79,0.383292,0.43,0.389164,0.0,0.50

In [24]:
std_T = df.describe().iloc[2:3, 1:].T
ci_low = []
ci_high = []
for i in df.columns[1:]:
    lst = []
    N = 2000
    for j in range(N):
        x = np.array(df[i]).reshape(-1, 1)
        x = StandardScaler().fit_transform(x)
        bootstrapSamples = resample(x, n_samples=100, replace=1)
        sd = bootstrapSamples.std() # ddof=1
        lst.append(sd)
        
    mean, std = np.array(lst).mean(), np.array(lst).std() # ddof=1
    conf_interval = stats.norm.interval(0.9, loc=mean, scale=std)
    ci_low.append(conf_interval[0])
    ci_high.append(conf_interval[1])
    
std_T.insert(1, 'ci_low_boundary', ci_low) 
std_T.insert(2, 'ci_high_boundary', ci_high)

D:\Softwares Installed\Anaconda\anaconda\lib\site-packages\scipy\stats\_distn_infrastructure.py:2098: RuntimeWarning: invalid value encountered in multiply
  lower_bound = _a * scale + loc
D:\Softwares Installed\Anaconda\anaconda\lib\site-packages\scipy\stats\_distn_infrastructure.py:2099: RuntimeWarning: invalid value encountered in multiply
  upper_bound = _b * scale + loc
D:\Softwares Installed\Anaconda\anaconda\lib\site-packages\scipy\stats\_distn_infrastructure.py:2098: RuntimeWarning: invalid value encountered in multiply
  lower_bound = _a * scale + loc
D:\Softwares Installed\Anaconda\anaconda\lib\site-packages\scipy\stats\_distn_infrastructure.py:2099: RuntimeWarning: invalid value encountered in multiply
  upper_bound = _b * scale + loc

In [25]:
std_T

             std  ci_low_boundary  ci_high_boundary
min_1   9.569975         0.873979          1.110371
max_1   4.394362         0.775831          1.194653
mean_1  5.335718         0.891416          1.093569
50%_1   5.440054         0.888579          1.098117
std_1   1.772153         0.892304          1.093806
25%_1   6.153590         0.912144          1.073123
75%_1   5.138925         0.854475          1.129207
min_2   0.000000              NaN               NaN
max_2   5.062729         0.922206          1.061869
mean_2  1.574164         0.903949          1.084714
50%_2   1.412244         0.890548          1.098089
std_2   0.884105         0.922270          1.069037
25%_2   0.946386         0.893137          1.093941
75%_2   2.125266         0.903472          1.082268
min_3   2.956462         0.936915          1.048560
max_3   4.875137         0.870093          1.114351
mean_3  4.008380         0.865759          1.116330
50%_3   4.036396         0.866744          1.122064
std_3   0.946710         0.808204          1.169855
25%_3   4.220658         0.873464          1.117681
75%_3   4.171628         0.868454          1.118428
min_4   0.000000              NaN               NaN
max_4   2.183625         0.911639          1.075226
mean_4  1.166114         0.936702          1.053888
50%_4   1.145586         0.935489          1.054451
std_4   0.458242         0.924890          1.060048
25%_4   0.843620         0.928051          1.059699
75%_4   1.552504         0.931754          1.055178
min_5   6.124001         0.749649          1.218908
max_5   5.741238         0.836296          1.136556
mean_5  5.675593         0.799090          1.181098
50%_5   5.813782         0.791414          1.179681
std_5   1.024898         0.809142          1.178428
25%_5   6.096465         0.793823          1.164045
75%_5   5.531720         0.804243          1.172042
min_6   0.045838        -0.163434          1.777262
max_6   2.518921         0.900625          1.088093
mean_6  1.154812         0.934191          1.055975
50%_6   1.086474         0.929543          1.061087
std_6   0.517617         0.936713          1.053135
25%_6   0.758584         0.921225          1.068492
75%_6   1.523599         0.933676          1.055827

#### Q1.c.(iv)

In my opinion, the three most important time-domain features are **mean**, **median** and **std**.  
It is because this three features' std seem smaller, which means they are more stable. And also, this three features can better describe the distribution of data.

---

## Q2

### a

I think the polynomial regression will have a lower training RSS than the linear regression.
Polynomial regression will fit the training set closer and better.

### b

When it comes to the test RSS, the polynomial regression will have a higher one than the linear regression. 
Because the true relationship between X and Y is linear and fitting the training set with polynomial regression will make the model too flexible, and thus introducing overfitting problem. So, the test set will be fit badly and have a higher RSS in the case of polynomial regression.

### c

Polynomial regression will have a lower training RSS than the linear regression.
It is because polynomial regression model is always flexible. Therefore, it fits the training set better with a lower training RSS.

### d

We don't have enough information on this one.
It is because in the question, only cubic regression is used. We don't know what's the exact polynomial relationship between X and Y. It could be quadratic, cubic or even much higher. Thus, the answer is we cannot decide.